---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-prod
  labels:
    app : myapp
    team: group:default/janus-authors
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-qa
  labels:
    app : myapp
    team: group:default/janus-authors
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-dev
  labels:
    app : myapp
    team: group:default/janus-authors
---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp-build
  labels:
    app : myapp
    team: group:default/janus-authors
